#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
for file in *; do
    # Exclude hidden files
    if [[ $file != .* ]]; then
        # Extract the part of the name after the first dash
        name=$(echo "$file" | cut -d '-' -f 2)
        echo "$name"
    fi
done
